# Generated by Django 5.0.4 on 2024-05-03 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='estudiante',
            new_name='estudiante_id',
        ),
    ]
